/* MER_lab_BD_R03: */

--> DROP – RESET COMPLETO DO BANCO
DROP TABLE FIN_Baixa        CASCADE CONSTRAINTS;
DROP TABLE FIN_Titulo_Pg    CASCADE CONSTRAINTS;
DROP TABLE FIN_Titulo_Rec   CASCADE CONSTRAINTS;
DROP TABLE NFS_Item         CASCADE CONSTRAINTS;
DROP TABLE NFS_Cabecalho    CASCADE CONSTRAINTS;
DROP TABLE NFE_Item         CASCADE CONSTRAINTS;
DROP TABLE NFE_Cabecalho    CASCADE CONSTRAINTS;
DROP TABLE VEN_Item_Pedido  CASCADE CONSTRAINTS;
DROP TABLE VEN_Pedido       CASCADE CONSTRAINTS;
DROP TABLE COM_Item_Pedido  CASCADE CONSTRAINTS;
DROP TABLE COM_Pedido       CASCADE CONSTRAINTS;
DROP TABLE EST_Produto      CASCADE CONSTRAINTS;
DROP TABLE EST_Local        CASCADE CONSTRAINTS;
DROP TABLE CAD_Produto      CASCADE CONSTRAINTS;
DROP TABLE CAD_Cliente      CASCADE CONSTRAINTS;
DROP TABLE CAD_Vendedor     CASCADE CONSTRAINTS;
DROP TABLE CAD_Fornecedor   CASCADE CONSTRAINTS;
DROP TABLE CAD_Pessoa       CASCADE CONSTRAINTS;


--> CADASTROS BÁSICOS
CREATE TABLE CAD_Pessoa (
	ID_Pessoa		VARCHAR(6) PRIMARY KEY,
	PES_Tipo		CHAR(1) NOT NULL,
	PES_CPF_CNPJ	VARCHAR(14) NOT NULL,
	PES_Nome		VARCHAR(100) NOT NULL,
	PES_Email		VARCHAR(100),
	PES_Telefone	VARCHAR(11),
	PES_Endereco	VARCHAR(100)
);

ALTER TABLE CAD_Pessoa ADD CONSTRAINT CK_PES_TIPO
	CHECK (PES_Tipo IN ('F','J'));

ALTER TABLE CAD_Pessoa ADD CONSTRAINT UK_PES_CPF_CNPJ
	UNIQUE (PES_CPF_CNPJ);


CREATE TABLE CAD_Fornecedor (
	ID_Fornecedor	VARCHAR(6) PRIMARY KEY,
	FOR_ID_Pessoa	VARCHAR(6) NOT NULL,
	FOR_Saldo_Fin	NUMERIC(10,2)
);

CREATE TABLE CAD_Vendedor (
	ID_Vendedor		VARCHAR(6) PRIMARY KEY,
	VEN_ID_Pessoa	VARCHAR(6) NOT NULL,
	VEN_Vendas		NUMERIC(10,2)
);

CREATE TABLE CAD_Cliente (
	ID_Cliente		VARCHAR(6) PRIMARY KEY,
	CLI_ID_Pessoa	VARCHAR(6) NOT NULL,
	CLI_Saldo_Fin	NUMERIC(10,2) NOT NULL
);


ALTER TABLE CAD_Fornecedor ADD CONSTRAINT FK_FOR_PESS
	FOREIGN KEY (FOR_ID_Pessoa) REFERENCES CAD_Pessoa (ID_Pessoa);

ALTER TABLE CAD_Vendedor ADD CONSTRAINT FK_VEN_PESS
	FOREIGN KEY (VEN_ID_Pessoa) REFERENCES CAD_Pessoa (ID_Pessoa);

ALTER TABLE CAD_Cliente ADD CONSTRAINT FK_CLI_PESS
	FOREIGN KEY (CLI_ID_Pessoa) REFERENCES CAD_Pessoa (ID_Pessoa);


--> PRODUTOS E ESTOQUE
CREATE TABLE CAD_Produto (
	ID_Produto		VARCHAR(6) PRIMARY KEY,
	PRO_Descricao	VARCHAR(100) NOT NULL,
	PRO_Preco_Com	NUMERIC(10,2),
	PRO_Preco_Ven	NUMERIC(10,2)
);

CREATE TABLE EST_Local (
	ID_EST_Local	VARCHAR(6) PRIMARY KEY,
	ESL_Descricao	VARCHAR(50) NOT NULL
);

CREATE TABLE EST_Produto (
	ID_Estoque		VARCHAR(6) PRIMARY KEY,
	EST_ID_Local	VARCHAR(6) NOT NULL,
	EST_ID_Produto	VARCHAR(6) NOT NULL,
	EST_Quantidade	NUMERIC(10,2),
	EST_Reserva		NUMERIC(10,2)
);

ALTER TABLE EST_Produto ADD CONSTRAINT FK_EST_PROD
	FOREIGN KEY (EST_ID_Produto) REFERENCES CAD_Produto (ID_Produto);

ALTER TABLE EST_Produto ADD CONSTRAINT FK_EST_LOCAL
	FOREIGN KEY (EST_ID_Local) REFERENCES EST_Local (ID_EST_Local);


--> COMPRAS
CREATE TABLE COM_Pedido (
	ID_P_Compra			VARCHAR(6) PRIMARY KEY,
	PCO_ID_Fornecedor 	VARCHAR(6) NOT NULL,
	PCO_Emissao			DATE NOT NULL,
	PCO_Valor			NUMERIC(10,2) NOT NULL,
	PCO_Pagamento		VARCHAR(6) NOT NULL,
	PCO_Num_Parc		NUMERIC NOT NULL
);

ALTER TABLE COM_Pedido ADD CONSTRAINT FK_PCO_FORN
	FOREIGN KEY (PCO_ID_Fornecedor) REFERENCES CAD_Fornecedor (ID_Fornecedor);


CREATE TABLE COM_Item_Pedido (
	ID_C_Item		VARCHAR(6) PRIMARY KEY,
	PCI_ID_P_Compra	VARCHAR(6) NOT NULL,
	PCI_ID_Produto	VARCHAR(6) NOT NULL,
	PCI_Qtde		NUMERIC(10,2) NOT NULL,
	PCI_V_Unit		NUMERIC(10,2) NOT NULL,
	PCI_Data_Entrega DATE
);

ALTER TABLE COM_Item_Pedido ADD CONSTRAINT FK_PCI_PCOM
	FOREIGN KEY (PCI_ID_P_Compra) REFERENCES COM_Pedido (ID_P_Compra);

ALTER TABLE COM_Item_Pedido ADD CONSTRAINT FK_PCI_PROD
	FOREIGN KEY (PCI_ID_Produto) REFERENCES CAD_Produto (ID_Produto);


--> NOTA FISCAL DE ENTRADA
CREATE TABLE NFE_Cabecalho (
	ID_NFE			VARCHAR(6) PRIMARY KEY,
	NFE_Numero		NUMBER NOT NULL,
    NFE_Serie		VARCHAR(3) NOT NULL,
	NFE_Emissao		DATE NOT NULL,
	NFE_Vencimento	DATE NOT NULL,
	NFE_Valor_Total	NUMERIC(10,2) NOT NULL,
	NFE_Chave		VARCHAR(44) NOT NULL
);

CREATE TABLE NFE_Item (
	ID_NFE_Item		VARCHAR(6) PRIMARY KEY,
	NEI_ID_NFE		VARCHAR(6) NOT NULL,
	NEI_ID_IPDC		VARCHAR(6) NOT NULL,
	NEI_ID_Prod		VARCHAR(6) NOT NULL,
	NEI_Qtde		NUMERIC(10,2) NOT NULL,
	NEI_Valor		NUMERIC(10,2) NOT NULL
);

ALTER TABLE NFE_Item ADD CONSTRAINT FK_NEI_NFE
	FOREIGN KEY (NEI_ID_NFE) REFERENCES NFE_Cabecalho (ID_NFE);

ALTER TABLE NFE_Item ADD CONSTRAINT FK_NEI_IPDC
	FOREIGN KEY (NEI_ID_IPDC) REFERENCES COM_Item_Pedido  (ID_C_Item);


ALTER TABLE NFE_Item ADD CONSTRAINT FK_NEI_PROD
	FOREIGN KEY (NEI_ID_Prod) REFERENCES CAD_Produto (ID_Produto);


--> VENDAS
CREATE TABLE VEN_Pedido (
	ID_P_Venda		VARCHAR(6) PRIMARY KEY,
	PVE_ID_Cliente	VARCHAR(6) NOT NULL,
	PVE_ID_Vendedor	VARCHAR(6) NOT NULL,
	PVE_Emissao		DATE NOT NULL,
	PVE_Valor		NUMERIC(10,2) NOT NULL,
	PVE_Pagamento	VARCHAR(6) NOT NULL,
	PVE_Num_Parc	NUMERIC DEFAULT 1
);

ALTER TABLE VEN_Pedido ADD CONSTRAINT FK_PVE_CLIE
	FOREIGN KEY (PVE_ID_Cliente) REFERENCES CAD_Cliente (ID_Cliente);

ALTER TABLE VEN_Pedido ADD CONSTRAINT FK_PVE_VEND
	FOREIGN KEY (PVE_ID_Vendedor) REFERENCES CAD_Vendedor (ID_Vendedor);


CREATE TABLE VEN_Item_Pedido (
	ID_V_Item		VARCHAR(6) PRIMARY KEY,
	PVI_ID_P_Venda	VARCHAR(6) NOT NULL,
	PVI_ID_Produto	VARCHAR(6) NOT NULL,
	PVI_Qtde		NUMERIC(10,2) NOT NULL,
	PVI_V_Unit		NUMERIC(10,2) NOT NULL
);

ALTER TABLE VEN_Item_Pedido ADD CONSTRAINT FK_PVI_PVEN
	FOREIGN KEY (PVI_ID_P_Venda) REFERENCES VEN_Pedido (ID_P_Venda);

ALTER TABLE VEN_Item_Pedido ADD CONSTRAINT FK_PVI_PROD
	FOREIGN KEY (PVI_ID_Produto) REFERENCES CAD_Produto (ID_Produto);


--> NOTA FISCAL DE SAÍDA
CREATE TABLE NFS_Cabecalho (
	ID_NFS			VARCHAR(6) PRIMARY KEY,
    NFS_Numero		NUMBER NOT NULL,
    NFS_Serie		VARCHAR(3) NOT NULL,
	NFS_Emissao		DATE NOT NULL,
	NFS_Vencimento	DATE NOT NULL,
	NFS_Valor_Total	NUMERIC(10,2) NOT NULL,
	NFS_Chave		VARCHAR(44) NOT NULL
);

CREATE TABLE NFS_Item (
	ID_NFS_Item		VARCHAR(6) PRIMARY KEY,
	NSI_ID_NFS		VARCHAR(6) NOT NULL,
    NSI_ID_IPDV		VARCHAR(6) NOT NULL,
	NSI_ID_Prod		VARCHAR(6) NOT NULL,
	NSI_Qtde		NUMERIC(10,2) NOT NULL,
	NSI_Valor		NUMERIC(10,2) NOT NULL
);

ALTER TABLE NFS_Item ADD CONSTRAINT FK_NFS_CAB
	FOREIGN KEY (NSI_ID_NFS) REFERENCES NFS_Cabecalho (ID_NFS);

ALTER TABLE NFS_Item ADD CONSTRAINT FK_NFS_IPDV
	FOREIGN KEY (NSI_ID_IPDV) REFERENCES VEN_Item_Pedido (ID_V_Item);
	

ALTER TABLE NFS_Item ADD CONSTRAINT FK_NFS_PROD
	FOREIGN KEY (NSI_ID_Prod) REFERENCES CAD_Produto (ID_Produto);


--> FINANCEIRO
CREATE TABLE FIN_Titulo_Pg (
	ID_Titulo_Pg	VARCHAR(6) PRIMARY KEY,
	FTP_ID_NFE		VARCHAR(6) NOT NULL,
	FTP_Parcela		VARCHAR(3),
	FTP_Valor		NUMERIC(10,2) NOT NULL,
	FTP_Vencimento	DATE NOT NULL,
	FTP_Saldo		NUMERIC(10,2)
);

ALTER TABLE FIN_Titulo_Pg ADD CONSTRAINT FK_FTP_NFE
	FOREIGN KEY (FTP_ID_NFE) REFERENCES NFE_Cabecalho (ID_NFE);


CREATE TABLE FIN_Titulo_Rec (
	ID_Titulo_Rec	VARCHAR(6) PRIMARY KEY,
	FTR_ID_NFS		VARCHAR(6) NOT NULL,
	FTR_Parcela		VARCHAR(3),
	FTR_Valor		NUMERIC(10,2) NOT NULL,
	FTR_Vencimento	DATE NOT NULL,
	FTR_Saldo		NUMERIC(10,2)
);

ALTER TABLE FIN_Titulo_Rec ADD CONSTRAINT FK_FTR_NFS
	FOREIGN KEY (FTR_ID_NFS) REFERENCES NFS_Cabecalho (ID_NFS);


CREATE TABLE FIN_Baixa (
	ID_Baixa		VARCHAR(6) PRIMARY KEY,
	FBX_ID_PG		VARCHAR(6),
	FBX_ID_RC		VARCHAR(6),
	FBX_Data		DATE NOT NULL,
	FBX_Valor		NUMERIC(10,2) NOT NULL,
	FBX_Tipo_Baixa	VARCHAR(3) NOT NULL,
	FBX_Historico	VARCHAR(150)
);

ALTER TABLE FIN_Baixa ADD CONSTRAINT FK_FBX_PG
	FOREIGN KEY (FBX_ID_PG) REFERENCES FIN_Titulo_Pg (ID_Titulo_Pg);

ALTER TABLE FIN_Baixa ADD CONSTRAINT FK_FBX_RC
	FOREIGN KEY (FBX_ID_RC) REFERENCES FIN_Titulo_Rec (ID_Titulo_Rec);

--> AJUSTES aplicado aos campos financeiros para manter uma rastreabilidade melhor, alterado de 6 apara 12 o tamanho dos campos.

-- REMOVER FKs DEPENDENTES
ALTER TABLE FIN_Baixa DROP CONSTRAINT FK_FBX_PG;
ALTER TABLE FIN_Baixa DROP CONSTRAINT FK_FBX_RC;

-- ALTERAR PKs (Títulos)
ALTER TABLE FIN_Titulo_Pg MODIFY ID_Titulo_Pg VARCHAR2(12);
ALTER TABLE FIN_Titulo_Rec MODIFY ID_Titulo_Rec VARCHAR2(12);

-- ALTERAR FKs (mesmo tamanho da PK)
ALTER TABLE FIN_Baixa MODIFY FBX_ID_PG VARCHAR2(12);
ALTER TABLE FIN_Baixa MODIFY FBX_ID_RC VARCHAR2(12);

-- RECRIAR AS FKs
ALTER TABLE FIN_Baixa ADD CONSTRAINT FK_FBX_PG
    FOREIGN KEY (FBX_ID_PG)
    REFERENCES FIN_Titulo_Pg (ID_Titulo_Pg);

ALTER TABLE FIN_Baixa ADD CONSTRAINT FK_FBX_RC
    FOREIGN KEY (FBX_ID_RC)
    REFERENCES FIN_Titulo_Rec (ID_Titulo_Rec);
