/* MER_lab_BD_R03: */

CREATE TABLE CAD_Fornecedor (
    ID_Fornecedor VARCHAR(6) PRIMARY KEY,
    FOR_ID_Pessoa VARCHAR(6) NOT NULL,
    FOR_Saldo_Fin NUMERIC
);

CREATE TABLE CAD_Vendedor (
    ID_Vendedor VARCHAR(6) PRIMARY KEY,
    VEN_ID_Pessoa VARCHAR(6) NOT NULL,
    VEN_Vendas NUMERIC
);

CREATE TABLE CAD_Produto (
    ID_Produto VARCHAR(6) PRIMARY KEY,
    PRO_Descricao VARCHAR(100) NOT NULL,
    PRO_Preco_Com NUMERIC,
    PRO_Preco_Ven NUMERIC
);

CREATE TABLE COM_Pedido (
    ID_P_Compra VARCHAR(6) PRIMARY KEY,
    PCO_ID_Fornecedor VARCHAR(6) NOT NULL,
    PCO_Emissao DATE NOT NULL,
    PCO_Valor NUMERIC NOT NULL,
    PCO_Pagamento VARCHAR(6) NOT NULL,
    PCO_Num_Parc NUMERIC NOT NULL
);

CREATE TABLE COM_Item_Pedido (
    ID_C_Item VARCHAR(6) PRIMARY KEY,
    PCI_ID_P_Compra VARCHAR(6) NOT NULL,
    PCI_ID_Produto VARCHAR(6) NOT NULL,
    PCI_Qtde NUMERIC NOT NULL,
    PCI_V_Unit NUMERIC NOT NULL,
    PCI_Data_Entrega DATE
);

CREATE TABLE NFE_Item (
    ID_NFE_Item VARCHAR(6) PRIMARY KEY,
    NEI_ID_NFE VARCHAR(6) NOT NULL,
    NEI_Qtde NUMERIC NOT NULL,
    NEI_Valor NUMERIC NOT NULL
);

CREATE TABLE NFE_Entrada (
    ID_NFE VARCHAR(6) PRIMARY KEY,
    NFE_Emissao DATE NOT NULL,
    NFE_Vencimento DATE NOT NULL,
    NFE_Valor_Total NUMERIC NOT NULL,
    NFE_Chave VARCHAR(44) NOT NULL
);

CREATE TABLE EST_Produto (
    ID_Estoque VARCHAR(6) PRIMARY KEY,
    EST_ID_Local VARCHAR(6) NOT NULL,
    EST_ID_Produto VARCHAR(6) NOT NULL,
    EST_Quantidade NUMERIC,
    EST_Reverva NUMERIC 
);

CREATE TABLE NFS_Item (
    ID_NFS_Item VARCHAR(6) PRIMARY KEY,
    NSI_ID_NFS VARCHAR(6) NOT NULL,
    NSI_Qtde NUMERIC NOT NULL,
    NSI_Valor NUMERIC NOT NULL
);

CREATE TABLE NFS_Cabecario (
    ID_NFS VARCHAR(6) PRIMARY KEY,
    NFS_Emissao DATE NOT NULL,
    NFS_Vencimento DATE NOT NULL,
    NFS_Valor_Total NUMERIC NOT NULL,
    NFS_Chave VARCHAR(44) NOT NULL
);

CREATE TABLE CAD_Cliente (
    ID_Cliente VARCHAR(6) PRIMARY KEY,
    CLI_ID_Pessoa VARCHAR(6) NOT NULL,
    CLI_Saldo_Fin NUMERIC NOT NULL
);

CREATE TABLE VEN_Pedido (
    ID_P_Venda VARCHAR(6) PRIMARY KEY,
    PVE_ID_Cliente VARCHAR(6) NOT NULL,
    PVE_ID_Vendedor VARCHAR(6) NOT NULL,
    PVE_Emissao DATE NOT NULL,
    PVE_Valor DATE NOT NULL,
    PVE_Pagamento VARCHAR(6) NOT NULL,
    PVE_Num_Parc NUMERIC DEFAULT 1
);

CREATE TABLE VEN_Item_Pedido (
    ID_V_Item VARCHAR(6) PRIMARY KEY,
    PVI_ID_P_Venda VARCHAR(6) NOT NULL,
    PVI_ID_Produto VARCHAR(6) NOT NULL,
    PVI_Qtde NUMERIC NOT NULL,
    PVI_V_Unit NUMERIC NOT NULL
);

CREATE TABLE FIN_Titulo_Pg (
    ID_Pagamento VARCHAR(6) PRIMARY KEY,
    FTP_ID_NFE VARCHAR(6) NOT NULL,
    FTP_Parcela VARCHAR(3),
    FTP_Valor NUMERIC NOT NULL,
    FTP_Vencimento DATE NOT NULL,
    FTP_Saldo NUMERIC
);

CREATE TABLE FIN_Baixa (
    ID_Baixa VARCHAR(6) PRIMARY KEY,
    FBX_ID_PG VARCHAR(6),
    FBX_ID_RC VARCHAR(6),
    FBX_Data DATE NOT NULL,
    FBX_Valor NUMERIC NOT NULL,
    FBX_Tipo_Baixa VARCHAR(3) NOT NULL,
    FBX_Historico VARCHAR(150)
);

CREATE TABLE FIN_Titulo_Rec (
    ID_Pagamento VARCHAR(6) PRIMARY KEY,
    FTP_ID_NFS VARCHAR(6) NOT NULL,
    FTR_Parcela VARCHAR(3),
    FTR_Valor NUMERIC NOT NULL,
    FTR_Vencimento DATE NOT NULL,
    FTR_Saldo NUMERIC
);

CREATE TABLE CAD_Pessoa (
    ID_Pessoa VARCHAR(6) PRIMARY KEY,
    PES_Tipo CHAR ENUM('F','J') NOT NULL,
    PES_CPF_CNPJ VARCHAR(14) NOT NULL,
    PES_Nome VARCHAR(100) NOT NULL,
    PES_Email VARCHAR(100),
    PES_Telefone VARCHAR(11),
    PES_Endereco VARCHAR(100)
);
 
ALTER TABLE CAD_Pessoa ADD CONSTRAINT CPF_CNPJ UNIQUE (PES_CPF_CNPJ);

CREATE TABLE EST_Local (
    ID_EST_Local VARCHAR(6) PRIMARY KEY,
    ESL_Descricao VARCHAR(50) NOT NULL
);
 
ALTER TABLE CAD_Fornecedor ADD CONSTRAINT FOR_PESS
    FOREIGN KEY (FOR_ID_Pessoa)
    REFERENCES CAD_Pessoa (ID_Pessoa);
 
ALTER TABLE CAD_Vendedor ADD CONSTRAINT VEN_PESS
    FOREIGN KEY (VEN_ID_Pessoa)
    REFERENCES CAD_Pessoa (ID_Pessoa);
 
ALTER TABLE COM_Pedido ADD CONSTRAINT PCO_FORN
    FOREIGN KEY (PCO_ID_Fornecedor)
    REFERENCES CAD_Fornecedor (ID_Fornecedor);
 
ALTER TABLE COM_Item_Pedido ADD CONSTRAINT PCI_PCOM
    FOREIGN KEY (PCI_ID_Produto)
    REFERENCES COM_Pedido (ID_P_Compra);
 
ALTER TABLE COM_Item_Pedido ADD CONSTRAINT PCI_PROD
    FOREIGN KEY (PCI_ID_P_Compra)
    REFERENCES CAD_Produto (ID_Produto);
 
ALTER TABLE NFE_Item ADD CONSTRAINT NEI_NFE
    FOREIGN KEY (NEI_ID_NFE)
    REFERENCES NFE_Entrada (ID_NFE);
 
ALTER TABLE EST_Produto ADD CONSTRAINT EST_PROD_CAD_PROD
    FOREIGN KEY (EST_ID_Produto)
    REFERENCES CAD_Produto (ID_Produto);
 
ALTER TABLE EST_Produto ADD CONSTRAINT ESP_ESL
    FOREIGN KEY (EST_ID_Local)
    REFERENCES EST_Local (ID_EST_Local);
 
ALTER TABLE NFS_Item ADD CONSTRAINT NF_CAB
    FOREIGN KEY (NSI_ID_NFS)
    REFERENCES NFS_Cabecario (ID_NFS);
 
ALTER TABLE CAD_Cliente ADD CONSTRAINT FK_CAD_Cliente
    FOREIGN KEY (CLI_ID_Pessoa)
    REFERENCES CAD_Pessoa (ID_Pessoa);
 
ALTER TABLE VEN_Pedido ADD CONSTRAINT PVE_CLIE
    FOREIGN KEY (PVE_ID_Cliente)
    REFERENCES CAD_Cliente (ID_Cliente);
 
ALTER TABLE VEN_Pedido ADD CONSTRAINT PVE_VEND
    FOREIGN KEY (PVE_ID_Vendedor)
    REFERENCES CAD_Vendedor (ID_Vendedor);
 
ALTER TABLE VEN_Item_Pedido ADD CONSTRAINT PVI_PVEN
    FOREIGN KEY (PVI_ID_P_Venda)
    REFERENCES VEN_Pedido (ID_P_Venda);
 
ALTER TABLE VEN_Item_Pedido ADD CONSTRAINT PVI_PROD
    FOREIGN KEY (PVI_ID_Produto)
    REFERENCES CAD_Produto (ID_Produto);
 
ALTER TABLE FIN_Titulo_Pg ADD CONSTRAINT FTP_NFE
    FOREIGN KEY (FTP_ID_NFE)
    REFERENCES NFE_Entrada (ID_NFE);
 
ALTER TABLE FIN_Baixa ADD CONSTRAINT FBX_FTP
    FOREIGN KEY (FBX_ID_PG)
    REFERENCES FIN_Titulo_Pg (ID_Pagamento);
 
ALTER TABLE FIN_Baixa ADD CONSTRAINT FBX_FTR
    FOREIGN KEY (FBX_ID_RC)
    REFERENCES FIN_Titulo_Rec (ID_Pagamento);
 
ALTER TABLE FIN_Titulo_Rec ADD CONSTRAINT FTR_NFS
    FOREIGN KEY (FTP_ID_NFS)
    REFERENCES NFS_Cabecario (ID_NFS);